Repository netlify/netlify-plugin-edge-handlers, pull requests merged in 2020-09, with the labels that each got.

#21 Remove esbuild
  index.js
  package-lock.json
  package.json
Labels: type: chore

#20 Add manifest generation
  index.js
Labels: type: feature

#22 Upload bundle to API
  index.js
  package-lock.json
  package.json
Labels: type: feature

#26 Fix package lockfile
  package-lock.json
Labels: type: chore

#27 Move upload process to its own file
  package.json
  rollup.config.js
  src/consts.js
  src/index.js
  src/upload.js
Labels: type: chore

#30 Remove `inputs` from `manifest.yml`
  manifest.yml
Labels: type: feature

#29 Fixes for the manifest generation.
  src/index.js
Labels: type: bug

#37 Log the list of handlers being bundled
  src/index.js
Labels: type: feature

#33 Add automated tests
  .eslintrc.json
  .github/workflows/workflow.yml
  .gitignore
  ava.config.js
  integration-test/edge-handlers/hello-world.js
  integration-test/package-lock.json
  integration-test/package.json
  package-lock.json
  package.json
  test/helpers/bundle.js
  test/helpers/handler.js
  test/helpers/run.js
  test/main.js
Labels: type: feature

#42 Fix Babel loading
  src/index.js
Labels: type: bug

#43 1.1.0
  package-lock.json
  package.json
Labels: type: chore

#47 Fail when api token is missing
  src/upload.js
Labels: type: bug

#52 Don't log in upload method
  src/index.js
  src/upload.js
Labels: type: chore

#56 Upgrade Netlify Build to `4.1.1`
  package-lock.json
  package.json
Labels: type: feature

#57 Add support for `build.edge_handlers`
  .gitignore
  integration-test/.gitignore
  manifest.yml
  src/index.js
  test/fixtures/config-dir/custom-edge-handlers/example.js
  test/fixtures/config-dir/netlify.toml
  test/main.js
Labels: type: feature

#58 Release `1.2.0`
  package-lock.json
  package.json
Labels: type: feature

#59 Validate `build.edge_handlers` exists
  package-lock.json
  package.json
  src/index.js
  test/fixtures/wrong-config-dir/netlify.toml
  test/main.js
Labels: type: feature

#60 Fix Windows support
  src/index.js
Labels: type: bug

#62 Update readme
  README.md
Labels: documentation, type: chore

#61 1.3.0
  package-lock.json
  package.json
Labels: type: feature

#63 Fix event
  src/index.js
Labels: type: feature

#64 1.3.1
  package-lock.json
  package.json
Labels: type: feature

#66 Make bundle filename consistent
  src/index.js
Labels: type: feature

#67 Cleanup previous bundles
  package-lock.json
  package.json
  src/index.js
Labels: type: feature

#70 1.4.0
  package-lock.json
  package.json
Labels: type: feature

#71 Move test fixture directory
  test/fixtures/integration-test/edge-handlers/data/states.json
  test/fixtures/integration-test/edge-handlers/example.js
  test/fixtures/integration-test/edge-handlers/hello-world.js
  test/fixtures/integration-test/index.html
  test/fixtures/integration-test/netlify.toml
  test/main.js
Labels: type: chore

#72 Fix Rollup warnings
  src/index.js
Labels: type: bug

#76 Compact bundle
  src/index.js
Labels: type: feature

#75 Improve error handling of Rollup
  src/index.js
  test/fixtures/syntax-error/edge-handlers/example.js
  test/fixtures/syntax-error/netlify.toml
  test/main.js
Labels: type: bug

#77 Simplify retrieving test fixtures
  test/helpers/bundle.js
  test/helpers/fixtures.js
  test/helpers/run.js
  test/main.js
Labels: type: chore

#78 1.5.0
  package-lock.json
  package.json
Labels: type: feature

#80 Small simplification of code generation
  src/index.js
Labels: type: feature

#81 Small refactoring of bundle generation
  src/index.js
Labels: type: chore

#79 fix: Add terser
  package-lock.json
  package.json
  src/index.js
Labels: enhancement, type: feature

#82 Apply Prettier to `README.md`
  README.md
Labels: type: chore

#83 1.6.0
  package-lock.json
  package.json
Labels: type: chore

#85 Report a plugin status
  src/index.js
Labels: type: feature

#87 1.7.0
  package-lock.json
  package.json
Labels: type: feature
