Repository netlify/netlify-plugin-edge-handlers, pull requests merged in 2022-01, with the labels that each got.

#828 chore: enable caching on CI
  .github/workflows/release-please.yml
  .github/workflows/workflow.yml
Labels: type: chore, automerge

#830 chore: tweak README.md
  README.md
Labels: type: chore

#829 fix: remove unused devDependencies, switch to c8, remove make-dir
  .gitignore
  package-lock.json
  package.json
  src/lib.js
  test/fixtures/integration-test/netlify/edge-handlers/hello_world.js
Labels: type: bug, automerge

#842 fix(deps): remove the unneeded `@types/node` dependency
  package-lock.json
  package.json
Labels: type: bug

#847 chore: fix Husky
  package-lock.json
  package.json
Labels: type: chore, automerge
